[2023-09-25 14:53:07,589] {processor.py:153} INFO - Started process (PID=196) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:07,595] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:53:07,599] {logging_mixin.py:115} INFO - [2023-09-25 14:53:07,598] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:07,819] {logging_mixin.py:115} INFO - [2023-09-25 14:53:07,805] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:53:07,839] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:07,941] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.371 seconds
[2023-09-25 14:53:38,186] {processor.py:153} INFO - Started process (PID=201) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:38,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:53:38,188] {logging_mixin.py:115} INFO - [2023-09-25 14:53:38,188] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:38,276] {logging_mixin.py:115} INFO - [2023-09-25 14:53:38,256] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:53:38,280] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:53:38,515] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.366 seconds
[2023-09-25 14:54:08,677] {processor.py:153} INFO - Started process (PID=206) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:08,678] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:54:08,679] {logging_mixin.py:115} INFO - [2023-09-25 14:54:08,679] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:08,733] {logging_mixin.py:115} INFO - [2023-09-25 14:54:08,721] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:54:08,738] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:08,763] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.090 seconds
[2023-09-25 14:54:38,815] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:38,817] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:54:38,818] {logging_mixin.py:115} INFO - [2023-09-25 14:54:38,818] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:38,947] {logging_mixin.py:115} INFO - [2023-09-25 14:54:38,943] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:54:38,948] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:54:38,969] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.161 seconds
[2023-09-25 14:55:09,063] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:09,065] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:55:09,067] {logging_mixin.py:115} INFO - [2023-09-25 14:55:09,066] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:09,118] {logging_mixin.py:115} INFO - [2023-09-25 14:55:09,113] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:55:09,119] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:09,143] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.083 seconds
[2023-09-25 14:55:39,307] {processor.py:153} INFO - Started process (PID=221) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:39,308] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:55:39,309] {logging_mixin.py:115} INFO - [2023-09-25 14:55:39,309] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:39,388] {logging_mixin.py:115} INFO - [2023-09-25 14:55:39,376] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:55:39,391] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:55:39,419] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.117 seconds
[2023-09-25 14:56:09,465] {processor.py:153} INFO - Started process (PID=226) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:09,466] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:56:09,467] {logging_mixin.py:115} INFO - [2023-09-25 14:56:09,467] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:09,508] {logging_mixin.py:115} INFO - [2023-09-25 14:56:09,503] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:56:09,510] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:09,532] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.072 seconds
[2023-09-25 14:56:39,605] {processor.py:153} INFO - Started process (PID=231) to work on /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:39,606] {processor.py:641} INFO - Processing file /opt/airflow/dags/1_dags.py for tasks to queue
[2023-09-25 14:56:39,607] {logging_mixin.py:115} INFO - [2023-09-25 14:56:39,607] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:39,650] {logging_mixin.py:115} INFO - [2023-09-25 14:56:39,646] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/1_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1_dags.py", line 8, in <module>
    from modules.covid_scraper import CovidScraper
ModuleNotFoundError: No module named 'modules.covid_scraper'
[2023-09-25 14:56:39,651] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/1_dags.py
[2023-09-25 14:56:39,678] {processor.py:161} INFO - Processing /opt/airflow/dags/1_dags.py took 0.076 seconds
